version: '3.9'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend
    volumes:
      - uploads:/app/uploads
    ports:
      - "8080:8080"
    environment:
      - DB_HOST=mariadb
      - DB_USER=root
      - DB_PASSWORD=root
      - DB_NAME=photolike
    depends_on:
      mariadb:
        condition: service_healthy

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_API_URL=http://localhost:8080
    depends_on:
      - backend

  mariadb:
    image: mariadb:10.4
    container_name: mariadb
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
    volumes:
      - mariadb_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "mariadb", "--silent"]
      interval: 10s
      timeout: 5s
      retries: 5
      
  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"  # Expose port 80 on the host machine to access the services
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf  # Custom Nginx configuration
    depends_on:
      - frontend
      - backend

volumes:
  mariadb_data:
  uploads:
